result_rdf(iri('https://example.org/flow-care'), iri('https://example.org/decision'), iri('https://example.org/permit'), default_graph).
result_rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/decision'), iri('https://example.org/review'), default_graph).
result_rdf(iri('https://example.org/flow-ads'), iri('https://example.org/decision'), iri('https://example.org/deny'), default_graph).
result_rdf(iri('https://example.org/flow-care'), iri('https://example.org/confidence'), literal('0.92', datatype('http://www.w3.org/2001/XMLSchema#decimal')), default_graph).
result_rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/confidence'), literal('0.63', datatype('http://www.w3.org/2001/XMLSchema#decimal')), default_graph).
result_rdf(iri('https://example.org/flow-care'), iri('https://example.org/status'), iri('https://example.org/executable_flow'), default_graph).
result_rdf(iri('https://example.org/flow-ads'), iri('https://example.org/status'), iri('https://example.org/blocked_flow'), default_graph).
result_rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/risk'), iri('https://example.org/trustworthiness_risk'), default_graph).
result_rdf(iri('https://example.org/flow-ads'), iri('https://example.org/risk'), iri('https://example.org/unwanted_disclosure'), default_graph).

clause(1,
       rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/healthcare-permission'), default_graph),
       true).
clause(2,
       rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/prohibition'), iri('https://example.org/marketing-prohibition'), default_graph),
       true).
clause(3,
       rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research-partner'), default_graph),
       true).
clause(4,
       rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph),
       true).
clause(5,
       rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph),
       true).
clause(6,
       rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/healthcare'), default_graph),
       true).
clause(7,
       rdf(iri('https://example.org/healthcare-permission'), iri('https://example.org/minTrust'), literal('0.80', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph),
       true).
clause(8,
       rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/ad-network'), default_graph),
       true).
clause(9,
       rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph),
       true).
clause(10,
       rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph),
       true).
clause(11,
       rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/marketing'), default_graph),
       true).
clause(12,
       rdf(iri('https://example.org/hospital-a'), iri('https://example.org/trustScore'), literal('0.92', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph),
       true).
clause(13,
       rdf(iri('https://example.org/small-clinic'), iri('https://example.org/trustScore'), literal('0.63', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph),
       true).
clause(15,
       rdf(iri('https://example.org/flow-care'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph),
       true).
clause(16,
       rdf(iri('https://example.org/flow-care'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph),
       true).
clause(17,
       rdf(iri('https://example.org/flow-care'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph),
       true).
clause(18,
       rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph),
       true).
clause(19,
       rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph),
       true).
clause(20,
       rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/source'), iri('https://example.org/small-clinic'), default_graph),
       true).
clause(21,
       rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph),
       true).
clause(22,
       rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph),
       true).
clause(23,
       rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph),
       true).
clause(24,
       rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph),
       true).
clause(25,
       rdf(iri('https://example.org/flow-ads'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph),
       true).
clause(26,
       rdf(iri('https://example.org/flow-ads'), iri('https://example.org/recipient'), iri('https://example.org/ad-network'), default_graph),
       true).
clause(27,
       rdf(iri('https://example.org/flow-ads'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph),
       true).
clause(28,
       rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph),
       true).
clause(29,
       rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedPurpose'), iri('https://example.org/marketing'), default_graph),
       true).
clause(31,
       flow_decision(var('Flow'), decision(var('Flow'), permit, confidence(var('Score')), status(executable_flow))),
       permitted_flow(var('Flow'), var('Score'))).
clause(32,
       flow_decision(var('Flow'), decision(var('Flow'), review, confidence(var('Score')), risk(trustworthiness_risk))),
       review_flow(var('Flow'), var('Score'))).
clause(33,
       flow_decision(var('Flow'), decision(var('Flow'), deny, status(blocked_flow), risk(unwanted_disclosure))),
       prohibited_flow(var('Flow'))).
clause(34,
       permitted_flow(var('Flow'), var('Score')),
       (flow_request(var('Flow'), var('Source'), var('Recipient'), var('Data'), var('Action'), var('Purpose')),
        policy_rule(odrl(permission), var('Rule'), var('Recipient'), var('Data'), var('Action'), var('Purpose')),
        rdf_number(var('Rule'), ex(minTrust), var('Minimum')),
        rdf_number(var('Source'), ex(trustScore), var('Score')),
        var('Score') >= var('Minimum'))).
clause(35,
       review_flow(var('Flow'), var('Score')),
       (flow_request(var('Flow'), var('Source'), var('Recipient'), var('Data'), var('Action'), var('Purpose')),
        policy_rule(odrl(permission), var('Rule'), var('Recipient'), var('Data'), var('Action'), var('Purpose')),
        rdf_number(var('Rule'), ex(minTrust), var('Minimum')),
        rdf_number(var('Source'), ex(trustScore), var('Score')),
        var('Score') < var('Minimum'))).
clause(36,
       prohibited_flow(var('Flow')),
       (flow_request(var('Flow'), anonymous(1), var('Recipient'), var('Data'), var('Action'), var('Purpose')),
        policy_rule(odrl(prohibition), anonymous(2), var('Recipient'), var('Data'), var('Action'), var('Purpose')))).
clause(37,
       flow_request(var('Flow'), var('Source'), var('Recipient'), var('Data'), var('Action'), var('Purpose')),
       (flow_resource(var('Flow'), var('Resource')),
        rdf_link(var('Resource'), ex(source), var('Source')),
        rdf_link(var('Resource'), ex(recipient), var('Recipient')),
        rdf_link(var('Resource'), ex(data), var('Data')),
        rdf_link(var('Resource'), ex(requestedAction), var('Action')),
        rdf_link(var('Resource'), ex(requestedPurpose), var('Purpose')))).
clause(38,
       policy_rule(var('Type'), var('Rule'), var('Recipient'), var('Data'), var('Action'), var('Purpose')),
       (rdf_link(ex('trust-policy'), var('Type'), var('Rule')),
        rdf_link(var('Rule'), odrl(assignee), var('Recipient')),
        rdf_link(var('Rule'), odrl(target), var('Data')),
        rdf_link(var('Rule'), odrl(action), var('Action')),
        rdf_link(var('Rule'), odrl(purpose), var('Purpose')))).
clause(39, flow_resource(flow_care, ex('flow-care')), true).
clause(40, flow_resource(flow_clinic, ex('flow-clinic')), true).
clause(41, flow_resource(flow_ads, ex('flow-ads')), true).
clause(42,
       rdf_link(var('Subject'), var('Predicate'), var('Object')),
       (iri_term(var('Subject'), var('SubjectIri')),
        iri_term(var('Predicate'), var('PredicateIri')),
        rdf(iri(var('SubjectIri')), iri(var('PredicateIri')), iri(var('ObjectIri')), default_graph),
        iri_term(var('Object'), var('ObjectIri')))).
clause(43,
       rdf_number(var('Subject'), var('Predicate'), var('Number')),
       (iri_term(var('Subject'), var('SubjectIri')),
        iri_term(var('Predicate'), var('PredicateIri')),
        rdf(iri(var('SubjectIri')), iri(var('PredicateIri')), literal(var('Text'), datatype(anonymous(1))), default_graph),
        atom_chars(var('Text'), var('Chars')),
        number_chars(var('Number'), var('Chars')))).
clause(44,
       iri_term(ex(var('Name')), var('Iri')),
       namespace_iri('https://example.org/', var('Name'), var('Iri'))).
clause(45,
       iri_term(odrl(var('Name')), var('Iri')),
       namespace_iri('http://www.w3.org/ns/odrl/2/', var('Name'), var('Iri'))).
clause(46,
       namespace_iri(var('Prefix'), var('Name'), var('Iri')),
       atom_concat(var('Prefix'), var('Name'), var('Iri'))).
clause(47,
       result_rdf(iri(var('FlowIri')), iri('https://example.org/decision'), iri(var('DecisionIri')), default_graph),
       (flow_decision(var('Flow'), var('DecisionTerm')),
        decision_name(var('DecisionTerm'), var('Decision')),
        flow_resource(var('Flow'), var('FlowResource')),
        iri_term(var('FlowResource'), var('FlowIri')),
        atom_concat('https://example.org/', var('Decision'), var('DecisionIri')))).
clause(48,
       result_rdf(iri(var('FlowIri')), iri('https://example.org/confidence'), literal(var('Text'), datatype('http://www.w3.org/2001/XMLSchema#decimal')), default_graph),
       (flow_decision(var('Flow'), var('DecisionTerm')),
        decision_has_confidence(var('DecisionTerm')),
        flow_resource(var('Flow'), var('FlowResource')),
        iri_term(var('FlowResource'), var('FlowIri')),
        flow_request(var('Flow'), var('Source'), anonymous(1), anonymous(2), anonymous(3), anonymous(4)),
        iri_term(var('Source'), var('SourceIri')),
        rdf(iri(var('SourceIri')), iri('https://example.org/trustScore'), literal(var('Text'), datatype(anonymous(5))), default_graph))).
clause(49,
       result_rdf(iri(var('FlowIri')), iri('https://example.org/status'), iri(var('StatusIri')), default_graph),
       (flow_decision(var('Flow'), var('DecisionTerm')),
        decision_status(var('DecisionTerm'), var('Status')),
        flow_resource(var('Flow'), var('FlowResource')),
        iri_term(var('FlowResource'), var('FlowIri')),
        atom_concat('https://example.org/', var('Status'), var('StatusIri')))).
clause(50,
       result_rdf(iri(var('FlowIri')), iri('https://example.org/risk'), iri(var('RiskIri')), default_graph),
       (flow_decision(var('Flow'), var('DecisionTerm')),
        decision_risk(var('DecisionTerm'), var('Risk')),
        flow_resource(var('Flow'), var('FlowResource')),
        iri_term(var('FlowResource'), var('FlowIri')),
        atom_concat('https://example.org/', var('Risk'), var('RiskIri')))).
clause(51,
       decision_name(decision(anonymous(1), permit, anonymous(2), anonymous(3)), permit),
       true).
clause(52,
       decision_name(decision(anonymous(1), review, anonymous(2), anonymous(3)), review),
       true).
clause(53, decision_name(decision(anonymous(1), deny, anonymous(2), anonymous(3)), deny), true).
clause(54,
       decision_has_confidence(decision(anonymous(1), permit, confidence(anonymous(2)), anonymous(3))),
       true).
clause(55,
       decision_has_confidence(decision(anonymous(1), review, confidence(anonymous(2)), anonymous(3))),
       true).
clause(56,
       decision_status(decision(anonymous(1), permit, anonymous(2), status(var('Status'))), var('Status')),
       true).
clause(57,
       decision_status(decision(anonymous(1), deny, status(var('Status')), anonymous(2)), var('Status')),
       true).
clause(58,
       decision_risk(decision(anonymous(1), review, anonymous(2), risk(var('Risk'))), var('Risk')),
       true).
clause(59,
       decision_risk(decision(anonymous(1), deny, anonymous(2), risk(var('Risk'))), var('Risk')),
       true).

step(result_rdf(iri('https://example.org/flow-care'), iri('https://example.org/decision'), iri('https://example.org/permit'), default_graph),
     rule(47),
     ['FlowIri' = 'https://example.org/flow-care',
      'DecisionIri' = 'https://example.org/permit',
      'Flow' = flow_care,
      'DecisionTerm' = decision(flow_care, permit, confidence(0.92), status(executable_flow)),
      'Decision' = permit,
      'FlowResource' = ex('flow-care')],
     [flow_decision(flow_care, decision(flow_care, permit, confidence(0.92), status(executable_flow))),
      decision_name(decision(flow_care, permit, confidence(0.92), status(executable_flow)), permit),
      flow_resource(flow_care, ex('flow-care')),
      iri_term(ex('flow-care'), 'https://example.org/flow-care'),
      atom_concat('https://example.org/', permit, 'https://example.org/permit')]).
step(flow_decision(flow_care, decision(flow_care, permit, confidence(0.92), status(executable_flow))),
     rule(31),
     ['Flow' = flow_care, 'Score' = 0.92],
     [permitted_flow(flow_care, 0.92)]).
step(permitted_flow(flow_care, 0.92),
     rule(34),
     ['Flow' = flow_care,
      'Score' = 0.92,
      'Source' = ex('hospital-a'),
      'Recipient' = ex('research-partner'),
      'Data' = ex('lab-result'),
      'Action' = odrl(use),
      'Purpose' = ex(healthcare),
      'Rule' = ex('healthcare-permission'),
      'Minimum' = 0.8],
     [flow_request(flow_care, ex('hospital-a'), ex('research-partner'), ex('lab-result'), odrl(use), ex(healthcare)),
      policy_rule(odrl(permission), ex('healthcare-permission'), ex('research-partner'), ex('lab-result'), odrl(use), ex(healthcare)),
      rdf_number(ex('healthcare-permission'), ex(minTrust), 0.8),
      rdf_number(ex('hospital-a'), ex(trustScore), 0.92),
      0.92 >= 0.8]).
step(flow_request(flow_care, ex('hospital-a'), ex('research-partner'), ex('lab-result'), odrl(use), ex(healthcare)),
     rule(37),
     ['Flow' = flow_care,
      'Source' = ex('hospital-a'),
      'Recipient' = ex('research-partner'),
      'Data' = ex('lab-result'),
      'Action' = odrl(use),
      'Purpose' = ex(healthcare),
      'Resource' = ex('flow-care')],
     [flow_resource(flow_care, ex('flow-care')),
      rdf_link(ex('flow-care'), ex(source), ex('hospital-a')),
      rdf_link(ex('flow-care'), ex(recipient), ex('research-partner')),
      rdf_link(ex('flow-care'), ex(data), ex('lab-result')),
      rdf_link(ex('flow-care'), ex(requestedAction), odrl(use)),
      rdf_link(ex('flow-care'), ex(requestedPurpose), ex(healthcare))]).
step(flow_resource(flow_care, ex('flow-care')), fact(39), [], []).
step(rdf_link(ex('flow-care'), ex(source), ex('hospital-a')),
     rule(42),
     ['Subject' = ex('flow-care'),
      'Predicate' = ex(source),
      'Object' = ex('hospital-a'),
      'SubjectIri' = 'https://example.org/flow-care',
      'PredicateIri' = 'https://example.org/source',
      'ObjectIri' = 'https://example.org/hospital-a'],
     [iri_term(ex('flow-care'), 'https://example.org/flow-care'),
      iri_term(ex(source), 'https://example.org/source'),
      rdf(iri('https://example.org/flow-care'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph),
      iri_term(ex('hospital-a'), 'https://example.org/hospital-a')]).
step(iri_term(ex('flow-care'), 'https://example.org/flow-care'),
     rule(44),
     ['Name' = 'flow-care', 'Iri' = 'https://example.org/flow-care'],
     [namespace_iri('https://example.org/', 'flow-care', 'https://example.org/flow-care')]).
step(namespace_iri('https://example.org/', 'flow-care', 'https://example.org/flow-care'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'flow-care',
      'Iri' = 'https://example.org/flow-care'],
     [atom_concat('https://example.org/', 'flow-care', 'https://example.org/flow-care')]).
step(atom_concat('https://example.org/', 'flow-care', 'https://example.org/flow-care'),
     builtin,
     [],
     []).
step(iri_term(ex(source), 'https://example.org/source'),
     rule(44),
     ['Name' = source, 'Iri' = 'https://example.org/source'],
     [namespace_iri('https://example.org/', source, 'https://example.org/source')]).
step(namespace_iri('https://example.org/', source, 'https://example.org/source'),
     rule(46),
     ['Prefix' = 'https://example.org/', 'Name' = source, 'Iri' = 'https://example.org/source'],
     [atom_concat('https://example.org/', source, 'https://example.org/source')]).
step(atom_concat('https://example.org/', source, 'https://example.org/source'), builtin, [], []).
step(rdf(iri('https://example.org/flow-care'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph),
     fact(15),
     [],
     []).
step(iri_term(ex('hospital-a'), 'https://example.org/hospital-a'),
     rule(44),
     ['Name' = 'hospital-a', 'Iri' = 'https://example.org/hospital-a'],
     [namespace_iri('https://example.org/', 'hospital-a', 'https://example.org/hospital-a')]).
step(namespace_iri('https://example.org/', 'hospital-a', 'https://example.org/hospital-a'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'hospital-a',
      'Iri' = 'https://example.org/hospital-a'],
     [atom_concat('https://example.org/', 'hospital-a', 'https://example.org/hospital-a')]).
step(atom_concat('https://example.org/', 'hospital-a', 'https://example.org/hospital-a'),
     builtin,
     [],
     []).
step(rdf_link(ex('flow-care'), ex(recipient), ex('research-partner')),
     rule(42),
     ['Subject' = ex('flow-care'),
      'Predicate' = ex(recipient),
      'Object' = ex('research-partner'),
      'SubjectIri' = 'https://example.org/flow-care',
      'PredicateIri' = 'https://example.org/recipient',
      'ObjectIri' = 'https://example.org/research-partner'],
     [iri_term(ex('flow-care'), 'https://example.org/flow-care'),
      iri_term(ex(recipient), 'https://example.org/recipient'),
      rdf(iri('https://example.org/flow-care'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph),
      iri_term(ex('research-partner'), 'https://example.org/research-partner')]).
step(iri_term(ex(recipient), 'https://example.org/recipient'),
     rule(44),
     ['Name' = recipient, 'Iri' = 'https://example.org/recipient'],
     [namespace_iri('https://example.org/', recipient, 'https://example.org/recipient')]).
step(namespace_iri('https://example.org/', recipient, 'https://example.org/recipient'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = recipient,
      'Iri' = 'https://example.org/recipient'],
     [atom_concat('https://example.org/', recipient, 'https://example.org/recipient')]).
step(atom_concat('https://example.org/', recipient, 'https://example.org/recipient'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/flow-care'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph),
     fact(16),
     [],
     []).
step(iri_term(ex('research-partner'), 'https://example.org/research-partner'),
     rule(44),
     ['Name' = 'research-partner', 'Iri' = 'https://example.org/research-partner'],
     [namespace_iri('https://example.org/', 'research-partner', 'https://example.org/research-partner')]).
step(namespace_iri('https://example.org/', 'research-partner', 'https://example.org/research-partner'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'research-partner',
      'Iri' = 'https://example.org/research-partner'],
     [atom_concat('https://example.org/', 'research-partner', 'https://example.org/research-partner')]).
step(atom_concat('https://example.org/', 'research-partner', 'https://example.org/research-partner'),
     builtin,
     [],
     []).
step(rdf_link(ex('flow-care'), ex(data), ex('lab-result')),
     rule(42),
     ['Subject' = ex('flow-care'),
      'Predicate' = ex(data),
      'Object' = ex('lab-result'),
      'SubjectIri' = 'https://example.org/flow-care',
      'PredicateIri' = 'https://example.org/data',
      'ObjectIri' = 'https://example.org/lab-result'],
     [iri_term(ex('flow-care'), 'https://example.org/flow-care'),
      iri_term(ex(data), 'https://example.org/data'),
      rdf(iri('https://example.org/flow-care'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph),
      iri_term(ex('lab-result'), 'https://example.org/lab-result')]).
step(iri_term(ex(data), 'https://example.org/data'),
     rule(44),
     ['Name' = data, 'Iri' = 'https://example.org/data'],
     [namespace_iri('https://example.org/', data, 'https://example.org/data')]).
step(namespace_iri('https://example.org/', data, 'https://example.org/data'),
     rule(46),
     ['Prefix' = 'https://example.org/', 'Name' = data, 'Iri' = 'https://example.org/data'],
     [atom_concat('https://example.org/', data, 'https://example.org/data')]).
step(atom_concat('https://example.org/', data, 'https://example.org/data'), builtin, [], []).
step(rdf(iri('https://example.org/flow-care'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph),
     fact(17),
     [],
     []).
step(iri_term(ex('lab-result'), 'https://example.org/lab-result'),
     rule(44),
     ['Name' = 'lab-result', 'Iri' = 'https://example.org/lab-result'],
     [namespace_iri('https://example.org/', 'lab-result', 'https://example.org/lab-result')]).
step(namespace_iri('https://example.org/', 'lab-result', 'https://example.org/lab-result'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'lab-result',
      'Iri' = 'https://example.org/lab-result'],
     [atom_concat('https://example.org/', 'lab-result', 'https://example.org/lab-result')]).
step(atom_concat('https://example.org/', 'lab-result', 'https://example.org/lab-result'),
     builtin,
     [],
     []).
step(rdf_link(ex('flow-care'), ex(requestedAction), odrl(use)),
     rule(42),
     ['Subject' = ex('flow-care'),
      'Predicate' = ex(requestedAction),
      'Object' = odrl(use),
      'SubjectIri' = 'https://example.org/flow-care',
      'PredicateIri' = 'https://example.org/requestedAction',
      'ObjectIri' = 'http://www.w3.org/ns/odrl/2/use'],
     [iri_term(ex('flow-care'), 'https://example.org/flow-care'),
      iri_term(ex(requestedAction), 'https://example.org/requestedAction'),
      rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph),
      iri_term(odrl(use), 'http://www.w3.org/ns/odrl/2/use')]).
step(iri_term(ex(requestedAction), 'https://example.org/requestedAction'),
     rule(44),
     ['Name' = requestedAction, 'Iri' = 'https://example.org/requestedAction'],
     [namespace_iri('https://example.org/', requestedAction, 'https://example.org/requestedAction')]).
step(namespace_iri('https://example.org/', requestedAction, 'https://example.org/requestedAction'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = requestedAction,
      'Iri' = 'https://example.org/requestedAction'],
     [atom_concat('https://example.org/', requestedAction, 'https://example.org/requestedAction')]).
step(atom_concat('https://example.org/', requestedAction, 'https://example.org/requestedAction'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph),
     fact(18),
     [],
     []).
step(iri_term(odrl(use), 'http://www.w3.org/ns/odrl/2/use'),
     rule(45),
     ['Name' = use, 'Iri' = 'http://www.w3.org/ns/odrl/2/use'],
     [namespace_iri('http://www.w3.org/ns/odrl/2/', use, 'http://www.w3.org/ns/odrl/2/use')]).
step(namespace_iri('http://www.w3.org/ns/odrl/2/', use, 'http://www.w3.org/ns/odrl/2/use'),
     rule(46),
     ['Prefix' = 'http://www.w3.org/ns/odrl/2/',
      'Name' = use,
      'Iri' = 'http://www.w3.org/ns/odrl/2/use'],
     [atom_concat('http://www.w3.org/ns/odrl/2/', use, 'http://www.w3.org/ns/odrl/2/use')]).
step(atom_concat('http://www.w3.org/ns/odrl/2/', use, 'http://www.w3.org/ns/odrl/2/use'),
     builtin,
     [],
     []).
step(rdf_link(ex('flow-care'), ex(requestedPurpose), ex(healthcare)),
     rule(42),
     ['Subject' = ex('flow-care'),
      'Predicate' = ex(requestedPurpose),
      'Object' = ex(healthcare),
      'SubjectIri' = 'https://example.org/flow-care',
      'PredicateIri' = 'https://example.org/requestedPurpose',
      'ObjectIri' = 'https://example.org/healthcare'],
     [iri_term(ex('flow-care'), 'https://example.org/flow-care'),
      iri_term(ex(requestedPurpose), 'https://example.org/requestedPurpose'),
      rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph),
      iri_term(ex(healthcare), 'https://example.org/healthcare')]).
step(iri_term(ex(requestedPurpose), 'https://example.org/requestedPurpose'),
     rule(44),
     ['Name' = requestedPurpose, 'Iri' = 'https://example.org/requestedPurpose'],
     [namespace_iri('https://example.org/', requestedPurpose, 'https://example.org/requestedPurpose')]).
step(namespace_iri('https://example.org/', requestedPurpose, 'https://example.org/requestedPurpose'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = requestedPurpose,
      'Iri' = 'https://example.org/requestedPurpose'],
     [atom_concat('https://example.org/', requestedPurpose, 'https://example.org/requestedPurpose')]).
step(atom_concat('https://example.org/', requestedPurpose, 'https://example.org/requestedPurpose'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph),
     fact(19),
     [],
     []).
step(iri_term(ex(healthcare), 'https://example.org/healthcare'),
     rule(44),
     ['Name' = healthcare, 'Iri' = 'https://example.org/healthcare'],
     [namespace_iri('https://example.org/', healthcare, 'https://example.org/healthcare')]).
step(namespace_iri('https://example.org/', healthcare, 'https://example.org/healthcare'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = healthcare,
      'Iri' = 'https://example.org/healthcare'],
     [atom_concat('https://example.org/', healthcare, 'https://example.org/healthcare')]).
step(atom_concat('https://example.org/', healthcare, 'https://example.org/healthcare'),
     builtin,
     [],
     []).
step(policy_rule(odrl(permission), ex('healthcare-permission'), ex('research-partner'), ex('lab-result'), odrl(use), ex(healthcare)),
     rule(38),
     ['Type' = odrl(permission),
      'Rule' = ex('healthcare-permission'),
      'Recipient' = ex('research-partner'),
      'Data' = ex('lab-result'),
      'Action' = odrl(use),
      'Purpose' = ex(healthcare)],
     [rdf_link(ex('trust-policy'), odrl(permission), ex('healthcare-permission')),
      rdf_link(ex('healthcare-permission'), odrl(assignee), ex('research-partner')),
      rdf_link(ex('healthcare-permission'), odrl(target), ex('lab-result')),
      rdf_link(ex('healthcare-permission'), odrl(action), odrl(use)),
      rdf_link(ex('healthcare-permission'), odrl(purpose), ex(healthcare))]).
step(rdf_link(ex('trust-policy'), odrl(permission), ex('healthcare-permission')),
     rule(42),
     ['Subject' = ex('trust-policy'),
      'Predicate' = odrl(permission),
      'Object' = ex('healthcare-permission'),
      'SubjectIri' = 'https://example.org/trust-policy',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/permission',
      'ObjectIri' = 'https://example.org/healthcare-permission'],
     [iri_term(ex('trust-policy'), 'https://example.org/trust-policy'),
      iri_term(odrl(permission), 'http://www.w3.org/ns/odrl/2/permission'),
      rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/healthcare-permission'), default_graph),
      iri_term(ex('healthcare-permission'), 'https://example.org/healthcare-permission')]).
step(iri_term(ex('trust-policy'), 'https://example.org/trust-policy'),
     rule(44),
     ['Name' = 'trust-policy', 'Iri' = 'https://example.org/trust-policy'],
     [namespace_iri('https://example.org/', 'trust-policy', 'https://example.org/trust-policy')]).
step(namespace_iri('https://example.org/', 'trust-policy', 'https://example.org/trust-policy'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'trust-policy',
      'Iri' = 'https://example.org/trust-policy'],
     [atom_concat('https://example.org/', 'trust-policy', 'https://example.org/trust-policy')]).
step(atom_concat('https://example.org/', 'trust-policy', 'https://example.org/trust-policy'),
     builtin,
     [],
     []).
step(iri_term(odrl(permission), 'http://www.w3.org/ns/odrl/2/permission'),
     rule(45),
     ['Name' = permission, 'Iri' = 'http://www.w3.org/ns/odrl/2/permission'],
     [namespace_iri('http://www.w3.org/ns/odrl/2/', permission, 'http://www.w3.org/ns/odrl/2/permission')]).
step(namespace_iri('http://www.w3.org/ns/odrl/2/', permission, 'http://www.w3.org/ns/odrl/2/permission'),
     rule(46),
     ['Prefix' = 'http://www.w3.org/ns/odrl/2/',
      'Name' = permission,
      'Iri' = 'http://www.w3.org/ns/odrl/2/permission'],
     [atom_concat('http://www.w3.org/ns/odrl/2/', permission, 'http://www.w3.org/ns/odrl/2/permission')]).
step(atom_concat('http://www.w3.org/ns/odrl/2/', permission, 'http://www.w3.org/ns/odrl/2/permission'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/healthcare-permission'), default_graph),
     fact(1),
     [],
     []).
step(iri_term(ex('healthcare-permission'), 'https://example.org/healthcare-permission'),
     rule(44),
     ['Name' = 'healthcare-permission', 'Iri' = 'https://example.org/healthcare-permission'],
     [namespace_iri('https://example.org/', 'healthcare-permission', 'https://example.org/healthcare-permission')]).
step(namespace_iri('https://example.org/', 'healthcare-permission', 'https://example.org/healthcare-permission'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'healthcare-permission',
      'Iri' = 'https://example.org/healthcare-permission'],
     [atom_concat('https://example.org/', 'healthcare-permission', 'https://example.org/healthcare-permission')]).
step(atom_concat('https://example.org/', 'healthcare-permission', 'https://example.org/healthcare-permission'),
     builtin,
     [],
     []).
step(rdf_link(ex('healthcare-permission'), odrl(assignee), ex('research-partner')),
     rule(42),
     ['Subject' = ex('healthcare-permission'),
      'Predicate' = odrl(assignee),
      'Object' = ex('research-partner'),
      'SubjectIri' = 'https://example.org/healthcare-permission',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/assignee',
      'ObjectIri' = 'https://example.org/research-partner'],
     [iri_term(ex('healthcare-permission'), 'https://example.org/healthcare-permission'),
      iri_term(odrl(assignee), 'http://www.w3.org/ns/odrl/2/assignee'),
      rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research-partner'), default_graph),
      iri_term(ex('research-partner'), 'https://example.org/research-partner')]).
step(iri_term(odrl(assignee), 'http://www.w3.org/ns/odrl/2/assignee'),
     rule(45),
     ['Name' = assignee, 'Iri' = 'http://www.w3.org/ns/odrl/2/assignee'],
     [namespace_iri('http://www.w3.org/ns/odrl/2/', assignee, 'http://www.w3.org/ns/odrl/2/assignee')]).
step(namespace_iri('http://www.w3.org/ns/odrl/2/', assignee, 'http://www.w3.org/ns/odrl/2/assignee'),
     rule(46),
     ['Prefix' = 'http://www.w3.org/ns/odrl/2/',
      'Name' = assignee,
      'Iri' = 'http://www.w3.org/ns/odrl/2/assignee'],
     [atom_concat('http://www.w3.org/ns/odrl/2/', assignee, 'http://www.w3.org/ns/odrl/2/assignee')]).
step(atom_concat('http://www.w3.org/ns/odrl/2/', assignee, 'http://www.w3.org/ns/odrl/2/assignee'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research-partner'), default_graph),
     fact(3),
     [],
     []).
step(rdf_link(ex('healthcare-permission'), odrl(target), ex('lab-result')),
     rule(42),
     ['Subject' = ex('healthcare-permission'),
      'Predicate' = odrl(target),
      'Object' = ex('lab-result'),
      'SubjectIri' = 'https://example.org/healthcare-permission',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/target',
      'ObjectIri' = 'https://example.org/lab-result'],
     [iri_term(ex('healthcare-permission'), 'https://example.org/healthcare-permission'),
      iri_term(odrl(target), 'http://www.w3.org/ns/odrl/2/target'),
      rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph),
      iri_term(ex('lab-result'), 'https://example.org/lab-result')]).
step(iri_term(odrl(target), 'http://www.w3.org/ns/odrl/2/target'),
     rule(45),
     ['Name' = target, 'Iri' = 'http://www.w3.org/ns/odrl/2/target'],
     [namespace_iri('http://www.w3.org/ns/odrl/2/', target, 'http://www.w3.org/ns/odrl/2/target')]).
step(namespace_iri('http://www.w3.org/ns/odrl/2/', target, 'http://www.w3.org/ns/odrl/2/target'),
     rule(46),
     ['Prefix' = 'http://www.w3.org/ns/odrl/2/',
      'Name' = target,
      'Iri' = 'http://www.w3.org/ns/odrl/2/target'],
     [atom_concat('http://www.w3.org/ns/odrl/2/', target, 'http://www.w3.org/ns/odrl/2/target')]).
step(atom_concat('http://www.w3.org/ns/odrl/2/', target, 'http://www.w3.org/ns/odrl/2/target'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph),
     fact(4),
     [],
     []).
step(rdf_link(ex('healthcare-permission'), odrl(action), odrl(use)),
     rule(42),
     ['Subject' = ex('healthcare-permission'),
      'Predicate' = odrl(action),
      'Object' = odrl(use),
      'SubjectIri' = 'https://example.org/healthcare-permission',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/action',
      'ObjectIri' = 'http://www.w3.org/ns/odrl/2/use'],
     [iri_term(ex('healthcare-permission'), 'https://example.org/healthcare-permission'),
      iri_term(odrl(action), 'http://www.w3.org/ns/odrl/2/action'),
      rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph),
      iri_term(odrl(use), 'http://www.w3.org/ns/odrl/2/use')]).
step(iri_term(odrl(action), 'http://www.w3.org/ns/odrl/2/action'),
     rule(45),
     ['Name' = action, 'Iri' = 'http://www.w3.org/ns/odrl/2/action'],
     [namespace_iri('http://www.w3.org/ns/odrl/2/', action, 'http://www.w3.org/ns/odrl/2/action')]).
step(namespace_iri('http://www.w3.org/ns/odrl/2/', action, 'http://www.w3.org/ns/odrl/2/action'),
     rule(46),
     ['Prefix' = 'http://www.w3.org/ns/odrl/2/',
      'Name' = action,
      'Iri' = 'http://www.w3.org/ns/odrl/2/action'],
     [atom_concat('http://www.w3.org/ns/odrl/2/', action, 'http://www.w3.org/ns/odrl/2/action')]).
step(atom_concat('http://www.w3.org/ns/odrl/2/', action, 'http://www.w3.org/ns/odrl/2/action'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph),
     fact(5),
     [],
     []).
step(rdf_link(ex('healthcare-permission'), odrl(purpose), ex(healthcare)),
     rule(42),
     ['Subject' = ex('healthcare-permission'),
      'Predicate' = odrl(purpose),
      'Object' = ex(healthcare),
      'SubjectIri' = 'https://example.org/healthcare-permission',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/purpose',
      'ObjectIri' = 'https://example.org/healthcare'],
     [iri_term(ex('healthcare-permission'), 'https://example.org/healthcare-permission'),
      iri_term(odrl(purpose), 'http://www.w3.org/ns/odrl/2/purpose'),
      rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/healthcare'), default_graph),
      iri_term(ex(healthcare), 'https://example.org/healthcare')]).
step(iri_term(odrl(purpose), 'http://www.w3.org/ns/odrl/2/purpose'),
     rule(45),
     ['Name' = purpose, 'Iri' = 'http://www.w3.org/ns/odrl/2/purpose'],
     [namespace_iri('http://www.w3.org/ns/odrl/2/', purpose, 'http://www.w3.org/ns/odrl/2/purpose')]).
step(namespace_iri('http://www.w3.org/ns/odrl/2/', purpose, 'http://www.w3.org/ns/odrl/2/purpose'),
     rule(46),
     ['Prefix' = 'http://www.w3.org/ns/odrl/2/',
      'Name' = purpose,
      'Iri' = 'http://www.w3.org/ns/odrl/2/purpose'],
     [atom_concat('http://www.w3.org/ns/odrl/2/', purpose, 'http://www.w3.org/ns/odrl/2/purpose')]).
step(atom_concat('http://www.w3.org/ns/odrl/2/', purpose, 'http://www.w3.org/ns/odrl/2/purpose'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/healthcare'), default_graph),
     fact(6),
     [],
     []).
step(rdf_number(ex('healthcare-permission'), ex(minTrust), 0.8),
     rule(43),
     ['Subject' = ex('healthcare-permission'),
      'Predicate' = ex(minTrust),
      'Number' = 0.8,
      'SubjectIri' = 'https://example.org/healthcare-permission',
      'PredicateIri' = 'https://example.org/minTrust',
      'Text' = '0.80',
      'Chars' = "0.80"],
     [iri_term(ex('healthcare-permission'), 'https://example.org/healthcare-permission'),
      iri_term(ex(minTrust), 'https://example.org/minTrust'),
      rdf(iri('https://example.org/healthcare-permission'), iri('https://example.org/minTrust'), literal('0.80', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph),
      atom_chars('0.80', "0.80"),
      number_chars(0.8, "0.80")]).
step(iri_term(ex(minTrust), 'https://example.org/minTrust'),
     rule(44),
     ['Name' = minTrust, 'Iri' = 'https://example.org/minTrust'],
     [namespace_iri('https://example.org/', minTrust, 'https://example.org/minTrust')]).
step(namespace_iri('https://example.org/', minTrust, 'https://example.org/minTrust'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = minTrust,
      'Iri' = 'https://example.org/minTrust'],
     [atom_concat('https://example.org/', minTrust, 'https://example.org/minTrust')]).
step(atom_concat('https://example.org/', minTrust, 'https://example.org/minTrust'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/healthcare-permission'), iri('https://example.org/minTrust'), literal('0.80', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph),
     fact(7),
     [],
     []).
step(atom_chars('0.80', "0.80"), builtin, [], []).
step(number_chars(0.8, "0.80"), builtin, [], []).
step(rdf_number(ex('hospital-a'), ex(trustScore), 0.92),
     rule(43),
     ['Subject' = ex('hospital-a'),
      'Predicate' = ex(trustScore),
      'Number' = 0.92,
      'SubjectIri' = 'https://example.org/hospital-a',
      'PredicateIri' = 'https://example.org/trustScore',
      'Text' = '0.92',
      'Chars' = "0.92"],
     [iri_term(ex('hospital-a'), 'https://example.org/hospital-a'),
      iri_term(ex(trustScore), 'https://example.org/trustScore'),
      rdf(iri('https://example.org/hospital-a'), iri('https://example.org/trustScore'), literal('0.92', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph),
      atom_chars('0.92', "0.92"),
      number_chars(0.92, "0.92")]).
step(iri_term(ex(trustScore), 'https://example.org/trustScore'),
     rule(44),
     ['Name' = trustScore, 'Iri' = 'https://example.org/trustScore'],
     [namespace_iri('https://example.org/', trustScore, 'https://example.org/trustScore')]).
step(namespace_iri('https://example.org/', trustScore, 'https://example.org/trustScore'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = trustScore,
      'Iri' = 'https://example.org/trustScore'],
     [atom_concat('https://example.org/', trustScore, 'https://example.org/trustScore')]).
step(atom_concat('https://example.org/', trustScore, 'https://example.org/trustScore'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/hospital-a'), iri('https://example.org/trustScore'), literal('0.92', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph),
     fact(12),
     [],
     []).
step(atom_chars('0.92', "0.92"), builtin, [], []).
step(number_chars(0.92, "0.92"), builtin, [], []).
step(0.92 >= 0.8, builtin, [], []).
step(decision_name(decision(flow_care, permit, confidence(0.92), status(executable_flow)), permit),
     fact(51),
     [],
     []).
step(atom_concat('https://example.org/', permit, 'https://example.org/permit'), builtin, [], []).
step(result_rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/decision'), iri('https://example.org/review'), default_graph),
     rule(47),
     ['FlowIri' = 'https://example.org/flow-clinic',
      'DecisionIri' = 'https://example.org/review',
      'Flow' = flow_clinic,
      'DecisionTerm' = decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk)),
      'Decision' = review,
      'FlowResource' = ex('flow-clinic')],
     [flow_decision(flow_clinic, decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk))),
      decision_name(decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk)), review),
      flow_resource(flow_clinic, ex('flow-clinic')),
      iri_term(ex('flow-clinic'), 'https://example.org/flow-clinic'),
      atom_concat('https://example.org/', review, 'https://example.org/review')]).
step(flow_decision(flow_clinic, decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk))),
     rule(32),
     ['Flow' = flow_clinic, 'Score' = 0.63],
     [review_flow(flow_clinic, 0.63)]).
step(review_flow(flow_clinic, 0.63),
     rule(35),
     ['Flow' = flow_clinic,
      'Score' = 0.63,
      'Source' = ex('small-clinic'),
      'Recipient' = ex('research-partner'),
      'Data' = ex('lab-result'),
      'Action' = odrl(use),
      'Purpose' = ex(healthcare),
      'Rule' = ex('healthcare-permission'),
      'Minimum' = 0.8],
     [flow_request(flow_clinic, ex('small-clinic'), ex('research-partner'), ex('lab-result'), odrl(use), ex(healthcare)),
      policy_rule(odrl(permission), ex('healthcare-permission'), ex('research-partner'), ex('lab-result'), odrl(use), ex(healthcare)),
      rdf_number(ex('healthcare-permission'), ex(minTrust), 0.8),
      rdf_number(ex('small-clinic'), ex(trustScore), 0.63),
      0.63 < 0.8]).
step(flow_request(flow_clinic, ex('small-clinic'), ex('research-partner'), ex('lab-result'), odrl(use), ex(healthcare)),
     rule(37),
     ['Flow' = flow_clinic,
      'Source' = ex('small-clinic'),
      'Recipient' = ex('research-partner'),
      'Data' = ex('lab-result'),
      'Action' = odrl(use),
      'Purpose' = ex(healthcare),
      'Resource' = ex('flow-clinic')],
     [flow_resource(flow_clinic, ex('flow-clinic')),
      rdf_link(ex('flow-clinic'), ex(source), ex('small-clinic')),
      rdf_link(ex('flow-clinic'), ex(recipient), ex('research-partner')),
      rdf_link(ex('flow-clinic'), ex(data), ex('lab-result')),
      rdf_link(ex('flow-clinic'), ex(requestedAction), odrl(use)),
      rdf_link(ex('flow-clinic'), ex(requestedPurpose), ex(healthcare))]).
step(flow_resource(flow_clinic, ex('flow-clinic')), fact(40), [], []).
step(rdf_link(ex('flow-clinic'), ex(source), ex('small-clinic')),
     rule(42),
     ['Subject' = ex('flow-clinic'),
      'Predicate' = ex(source),
      'Object' = ex('small-clinic'),
      'SubjectIri' = 'https://example.org/flow-clinic',
      'PredicateIri' = 'https://example.org/source',
      'ObjectIri' = 'https://example.org/small-clinic'],
     [iri_term(ex('flow-clinic'), 'https://example.org/flow-clinic'),
      iri_term(ex(source), 'https://example.org/source'),
      rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/source'), iri('https://example.org/small-clinic'), default_graph),
      iri_term(ex('small-clinic'), 'https://example.org/small-clinic')]).
step(iri_term(ex('flow-clinic'), 'https://example.org/flow-clinic'),
     rule(44),
     ['Name' = 'flow-clinic', 'Iri' = 'https://example.org/flow-clinic'],
     [namespace_iri('https://example.org/', 'flow-clinic', 'https://example.org/flow-clinic')]).
step(namespace_iri('https://example.org/', 'flow-clinic', 'https://example.org/flow-clinic'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'flow-clinic',
      'Iri' = 'https://example.org/flow-clinic'],
     [atom_concat('https://example.org/', 'flow-clinic', 'https://example.org/flow-clinic')]).
step(atom_concat('https://example.org/', 'flow-clinic', 'https://example.org/flow-clinic'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/source'), iri('https://example.org/small-clinic'), default_graph),
     fact(20),
     [],
     []).
step(iri_term(ex('small-clinic'), 'https://example.org/small-clinic'),
     rule(44),
     ['Name' = 'small-clinic', 'Iri' = 'https://example.org/small-clinic'],
     [namespace_iri('https://example.org/', 'small-clinic', 'https://example.org/small-clinic')]).
step(namespace_iri('https://example.org/', 'small-clinic', 'https://example.org/small-clinic'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'small-clinic',
      'Iri' = 'https://example.org/small-clinic'],
     [atom_concat('https://example.org/', 'small-clinic', 'https://example.org/small-clinic')]).
step(atom_concat('https://example.org/', 'small-clinic', 'https://example.org/small-clinic'),
     builtin,
     [],
     []).
step(rdf_link(ex('flow-clinic'), ex(recipient), ex('research-partner')),
     rule(42),
     ['Subject' = ex('flow-clinic'),
      'Predicate' = ex(recipient),
      'Object' = ex('research-partner'),
      'SubjectIri' = 'https://example.org/flow-clinic',
      'PredicateIri' = 'https://example.org/recipient',
      'ObjectIri' = 'https://example.org/research-partner'],
     [iri_term(ex('flow-clinic'), 'https://example.org/flow-clinic'),
      iri_term(ex(recipient), 'https://example.org/recipient'),
      rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph),
      iri_term(ex('research-partner'), 'https://example.org/research-partner')]).
step(rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph),
     fact(21),
     [],
     []).
step(rdf_link(ex('flow-clinic'), ex(data), ex('lab-result')),
     rule(42),
     ['Subject' = ex('flow-clinic'),
      'Predicate' = ex(data),
      'Object' = ex('lab-result'),
      'SubjectIri' = 'https://example.org/flow-clinic',
      'PredicateIri' = 'https://example.org/data',
      'ObjectIri' = 'https://example.org/lab-result'],
     [iri_term(ex('flow-clinic'), 'https://example.org/flow-clinic'),
      iri_term(ex(data), 'https://example.org/data'),
      rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph),
      iri_term(ex('lab-result'), 'https://example.org/lab-result')]).
step(rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph),
     fact(22),
     [],
     []).
step(rdf_link(ex('flow-clinic'), ex(requestedAction), odrl(use)),
     rule(42),
     ['Subject' = ex('flow-clinic'),
      'Predicate' = ex(requestedAction),
      'Object' = odrl(use),
      'SubjectIri' = 'https://example.org/flow-clinic',
      'PredicateIri' = 'https://example.org/requestedAction',
      'ObjectIri' = 'http://www.w3.org/ns/odrl/2/use'],
     [iri_term(ex('flow-clinic'), 'https://example.org/flow-clinic'),
      iri_term(ex(requestedAction), 'https://example.org/requestedAction'),
      rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph),
      iri_term(odrl(use), 'http://www.w3.org/ns/odrl/2/use')]).
step(rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph),
     fact(23),
     [],
     []).
step(rdf_link(ex('flow-clinic'), ex(requestedPurpose), ex(healthcare)),
     rule(42),
     ['Subject' = ex('flow-clinic'),
      'Predicate' = ex(requestedPurpose),
      'Object' = ex(healthcare),
      'SubjectIri' = 'https://example.org/flow-clinic',
      'PredicateIri' = 'https://example.org/requestedPurpose',
      'ObjectIri' = 'https://example.org/healthcare'],
     [iri_term(ex('flow-clinic'), 'https://example.org/flow-clinic'),
      iri_term(ex(requestedPurpose), 'https://example.org/requestedPurpose'),
      rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph),
      iri_term(ex(healthcare), 'https://example.org/healthcare')]).
step(rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph),
     fact(24),
     [],
     []).
step(rdf_number(ex('small-clinic'), ex(trustScore), 0.63),
     rule(43),
     ['Subject' = ex('small-clinic'),
      'Predicate' = ex(trustScore),
      'Number' = 0.63,
      'SubjectIri' = 'https://example.org/small-clinic',
      'PredicateIri' = 'https://example.org/trustScore',
      'Text' = '0.63',
      'Chars' = "0.63"],
     [iri_term(ex('small-clinic'), 'https://example.org/small-clinic'),
      iri_term(ex(trustScore), 'https://example.org/trustScore'),
      rdf(iri('https://example.org/small-clinic'), iri('https://example.org/trustScore'), literal('0.63', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph),
      atom_chars('0.63', "0.63"),
      number_chars(0.63, "0.63")]).
step(rdf(iri('https://example.org/small-clinic'), iri('https://example.org/trustScore'), literal('0.63', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph),
     fact(13),
     [],
     []).
step(atom_chars('0.63', "0.63"), builtin, [], []).
step(number_chars(0.63, "0.63"), builtin, [], []).
step(0.63 < 0.8, builtin, [], []).
step(decision_name(decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk)), review),
     fact(52),
     [],
     []).
step(atom_concat('https://example.org/', review, 'https://example.org/review'), builtin, [], []).
step(result_rdf(iri('https://example.org/flow-ads'), iri('https://example.org/decision'), iri('https://example.org/deny'), default_graph),
     rule(47),
     ['FlowIri' = 'https://example.org/flow-ads',
      'DecisionIri' = 'https://example.org/deny',
      'Flow' = flow_ads,
      'DecisionTerm' = decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure)),
      'Decision' = deny,
      'FlowResource' = ex('flow-ads')],
     [flow_decision(flow_ads, decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure))),
      decision_name(decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure)), deny),
      flow_resource(flow_ads, ex('flow-ads')),
      iri_term(ex('flow-ads'), 'https://example.org/flow-ads'),
      atom_concat('https://example.org/', deny, 'https://example.org/deny')]).
step(flow_decision(flow_ads, decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure))),
     rule(33),
     ['Flow' = flow_ads],
     [prohibited_flow(flow_ads)]).
step(prohibited_flow(flow_ads),
     rule(36),
     ['Flow' = flow_ads,
      'Recipient' = ex('ad-network'),
      'Data' = ex('lab-result'),
      'Action' = odrl(distribute),
      'Purpose' = ex(marketing)],
     [flow_request(flow_ads, ex('hospital-a'), ex('ad-network'), ex('lab-result'), odrl(distribute), ex(marketing)),
      policy_rule(odrl(prohibition), ex('marketing-prohibition'), ex('ad-network'), ex('lab-result'), odrl(distribute), ex(marketing))]).
step(flow_request(flow_ads, ex('hospital-a'), ex('ad-network'), ex('lab-result'), odrl(distribute), ex(marketing)),
     rule(37),
     ['Flow' = flow_ads,
      'Source' = ex('hospital-a'),
      'Recipient' = ex('ad-network'),
      'Data' = ex('lab-result'),
      'Action' = odrl(distribute),
      'Purpose' = ex(marketing),
      'Resource' = ex('flow-ads')],
     [flow_resource(flow_ads, ex('flow-ads')),
      rdf_link(ex('flow-ads'), ex(source), ex('hospital-a')),
      rdf_link(ex('flow-ads'), ex(recipient), ex('ad-network')),
      rdf_link(ex('flow-ads'), ex(data), ex('lab-result')),
      rdf_link(ex('flow-ads'), ex(requestedAction), odrl(distribute)),
      rdf_link(ex('flow-ads'), ex(requestedPurpose), ex(marketing))]).
step(flow_resource(flow_ads, ex('flow-ads')), fact(41), [], []).
step(rdf_link(ex('flow-ads'), ex(source), ex('hospital-a')),
     rule(42),
     ['Subject' = ex('flow-ads'),
      'Predicate' = ex(source),
      'Object' = ex('hospital-a'),
      'SubjectIri' = 'https://example.org/flow-ads',
      'PredicateIri' = 'https://example.org/source',
      'ObjectIri' = 'https://example.org/hospital-a'],
     [iri_term(ex('flow-ads'), 'https://example.org/flow-ads'),
      iri_term(ex(source), 'https://example.org/source'),
      rdf(iri('https://example.org/flow-ads'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph),
      iri_term(ex('hospital-a'), 'https://example.org/hospital-a')]).
step(iri_term(ex('flow-ads'), 'https://example.org/flow-ads'),
     rule(44),
     ['Name' = 'flow-ads', 'Iri' = 'https://example.org/flow-ads'],
     [namespace_iri('https://example.org/', 'flow-ads', 'https://example.org/flow-ads')]).
step(namespace_iri('https://example.org/', 'flow-ads', 'https://example.org/flow-ads'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'flow-ads',
      'Iri' = 'https://example.org/flow-ads'],
     [atom_concat('https://example.org/', 'flow-ads', 'https://example.org/flow-ads')]).
step(atom_concat('https://example.org/', 'flow-ads', 'https://example.org/flow-ads'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/flow-ads'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph),
     fact(25),
     [],
     []).
step(rdf_link(ex('flow-ads'), ex(recipient), ex('ad-network')),
     rule(42),
     ['Subject' = ex('flow-ads'),
      'Predicate' = ex(recipient),
      'Object' = ex('ad-network'),
      'SubjectIri' = 'https://example.org/flow-ads',
      'PredicateIri' = 'https://example.org/recipient',
      'ObjectIri' = 'https://example.org/ad-network'],
     [iri_term(ex('flow-ads'), 'https://example.org/flow-ads'),
      iri_term(ex(recipient), 'https://example.org/recipient'),
      rdf(iri('https://example.org/flow-ads'), iri('https://example.org/recipient'), iri('https://example.org/ad-network'), default_graph),
      iri_term(ex('ad-network'), 'https://example.org/ad-network')]).
step(rdf(iri('https://example.org/flow-ads'), iri('https://example.org/recipient'), iri('https://example.org/ad-network'), default_graph),
     fact(26),
     [],
     []).
step(iri_term(ex('ad-network'), 'https://example.org/ad-network'),
     rule(44),
     ['Name' = 'ad-network', 'Iri' = 'https://example.org/ad-network'],
     [namespace_iri('https://example.org/', 'ad-network', 'https://example.org/ad-network')]).
step(namespace_iri('https://example.org/', 'ad-network', 'https://example.org/ad-network'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'ad-network',
      'Iri' = 'https://example.org/ad-network'],
     [atom_concat('https://example.org/', 'ad-network', 'https://example.org/ad-network')]).
step(atom_concat('https://example.org/', 'ad-network', 'https://example.org/ad-network'),
     builtin,
     [],
     []).
step(rdf_link(ex('flow-ads'), ex(data), ex('lab-result')),
     rule(42),
     ['Subject' = ex('flow-ads'),
      'Predicate' = ex(data),
      'Object' = ex('lab-result'),
      'SubjectIri' = 'https://example.org/flow-ads',
      'PredicateIri' = 'https://example.org/data',
      'ObjectIri' = 'https://example.org/lab-result'],
     [iri_term(ex('flow-ads'), 'https://example.org/flow-ads'),
      iri_term(ex(data), 'https://example.org/data'),
      rdf(iri('https://example.org/flow-ads'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph),
      iri_term(ex('lab-result'), 'https://example.org/lab-result')]).
step(rdf(iri('https://example.org/flow-ads'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph),
     fact(27),
     [],
     []).
step(rdf_link(ex('flow-ads'), ex(requestedAction), odrl(distribute)),
     rule(42),
     ['Subject' = ex('flow-ads'),
      'Predicate' = ex(requestedAction),
      'Object' = odrl(distribute),
      'SubjectIri' = 'https://example.org/flow-ads',
      'PredicateIri' = 'https://example.org/requestedAction',
      'ObjectIri' = 'http://www.w3.org/ns/odrl/2/distribute'],
     [iri_term(ex('flow-ads'), 'https://example.org/flow-ads'),
      iri_term(ex(requestedAction), 'https://example.org/requestedAction'),
      rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph),
      iri_term(odrl(distribute), 'http://www.w3.org/ns/odrl/2/distribute')]).
step(rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph),
     fact(28),
     [],
     []).
step(iri_term(odrl(distribute), 'http://www.w3.org/ns/odrl/2/distribute'),
     rule(45),
     ['Name' = distribute, 'Iri' = 'http://www.w3.org/ns/odrl/2/distribute'],
     [namespace_iri('http://www.w3.org/ns/odrl/2/', distribute, 'http://www.w3.org/ns/odrl/2/distribute')]).
step(namespace_iri('http://www.w3.org/ns/odrl/2/', distribute, 'http://www.w3.org/ns/odrl/2/distribute'),
     rule(46),
     ['Prefix' = 'http://www.w3.org/ns/odrl/2/',
      'Name' = distribute,
      'Iri' = 'http://www.w3.org/ns/odrl/2/distribute'],
     [atom_concat('http://www.w3.org/ns/odrl/2/', distribute, 'http://www.w3.org/ns/odrl/2/distribute')]).
step(atom_concat('http://www.w3.org/ns/odrl/2/', distribute, 'http://www.w3.org/ns/odrl/2/distribute'),
     builtin,
     [],
     []).
step(rdf_link(ex('flow-ads'), ex(requestedPurpose), ex(marketing)),
     rule(42),
     ['Subject' = ex('flow-ads'),
      'Predicate' = ex(requestedPurpose),
      'Object' = ex(marketing),
      'SubjectIri' = 'https://example.org/flow-ads',
      'PredicateIri' = 'https://example.org/requestedPurpose',
      'ObjectIri' = 'https://example.org/marketing'],
     [iri_term(ex('flow-ads'), 'https://example.org/flow-ads'),
      iri_term(ex(requestedPurpose), 'https://example.org/requestedPurpose'),
      rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedPurpose'), iri('https://example.org/marketing'), default_graph),
      iri_term(ex(marketing), 'https://example.org/marketing')]).
step(rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedPurpose'), iri('https://example.org/marketing'), default_graph),
     fact(29),
     [],
     []).
step(iri_term(ex(marketing), 'https://example.org/marketing'),
     rule(44),
     ['Name' = marketing, 'Iri' = 'https://example.org/marketing'],
     [namespace_iri('https://example.org/', marketing, 'https://example.org/marketing')]).
step(namespace_iri('https://example.org/', marketing, 'https://example.org/marketing'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = marketing,
      'Iri' = 'https://example.org/marketing'],
     [atom_concat('https://example.org/', marketing, 'https://example.org/marketing')]).
step(atom_concat('https://example.org/', marketing, 'https://example.org/marketing'),
     builtin,
     [],
     []).
step(policy_rule(odrl(prohibition), ex('marketing-prohibition'), ex('ad-network'), ex('lab-result'), odrl(distribute), ex(marketing)),
     rule(38),
     ['Type' = odrl(prohibition),
      'Rule' = ex('marketing-prohibition'),
      'Recipient' = ex('ad-network'),
      'Data' = ex('lab-result'),
      'Action' = odrl(distribute),
      'Purpose' = ex(marketing)],
     [rdf_link(ex('trust-policy'), odrl(prohibition), ex('marketing-prohibition')),
      rdf_link(ex('marketing-prohibition'), odrl(assignee), ex('ad-network')),
      rdf_link(ex('marketing-prohibition'), odrl(target), ex('lab-result')),
      rdf_link(ex('marketing-prohibition'), odrl(action), odrl(distribute)),
      rdf_link(ex('marketing-prohibition'), odrl(purpose), ex(marketing))]).
step(rdf_link(ex('trust-policy'), odrl(prohibition), ex('marketing-prohibition')),
     rule(42),
     ['Subject' = ex('trust-policy'),
      'Predicate' = odrl(prohibition),
      'Object' = ex('marketing-prohibition'),
      'SubjectIri' = 'https://example.org/trust-policy',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/prohibition',
      'ObjectIri' = 'https://example.org/marketing-prohibition'],
     [iri_term(ex('trust-policy'), 'https://example.org/trust-policy'),
      iri_term(odrl(prohibition), 'http://www.w3.org/ns/odrl/2/prohibition'),
      rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/prohibition'), iri('https://example.org/marketing-prohibition'), default_graph),
      iri_term(ex('marketing-prohibition'), 'https://example.org/marketing-prohibition')]).
step(iri_term(odrl(prohibition), 'http://www.w3.org/ns/odrl/2/prohibition'),
     rule(45),
     ['Name' = prohibition, 'Iri' = 'http://www.w3.org/ns/odrl/2/prohibition'],
     [namespace_iri('http://www.w3.org/ns/odrl/2/', prohibition, 'http://www.w3.org/ns/odrl/2/prohibition')]).
step(namespace_iri('http://www.w3.org/ns/odrl/2/', prohibition, 'http://www.w3.org/ns/odrl/2/prohibition'),
     rule(46),
     ['Prefix' = 'http://www.w3.org/ns/odrl/2/',
      'Name' = prohibition,
      'Iri' = 'http://www.w3.org/ns/odrl/2/prohibition'],
     [atom_concat('http://www.w3.org/ns/odrl/2/', prohibition, 'http://www.w3.org/ns/odrl/2/prohibition')]).
step(atom_concat('http://www.w3.org/ns/odrl/2/', prohibition, 'http://www.w3.org/ns/odrl/2/prohibition'),
     builtin,
     [],
     []).
step(rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/prohibition'), iri('https://example.org/marketing-prohibition'), default_graph),
     fact(2),
     [],
     []).
step(iri_term(ex('marketing-prohibition'), 'https://example.org/marketing-prohibition'),
     rule(44),
     ['Name' = 'marketing-prohibition', 'Iri' = 'https://example.org/marketing-prohibition'],
     [namespace_iri('https://example.org/', 'marketing-prohibition', 'https://example.org/marketing-prohibition')]).
step(namespace_iri('https://example.org/', 'marketing-prohibition', 'https://example.org/marketing-prohibition'),
     rule(46),
     ['Prefix' = 'https://example.org/',
      'Name' = 'marketing-prohibition',
      'Iri' = 'https://example.org/marketing-prohibition'],
     [atom_concat('https://example.org/', 'marketing-prohibition', 'https://example.org/marketing-prohibition')]).
step(atom_concat('https://example.org/', 'marketing-prohibition', 'https://example.org/marketing-prohibition'),
     builtin,
     [],
     []).
step(rdf_link(ex('marketing-prohibition'), odrl(assignee), ex('ad-network')),
     rule(42),
     ['Subject' = ex('marketing-prohibition'),
      'Predicate' = odrl(assignee),
      'Object' = ex('ad-network'),
      'SubjectIri' = 'https://example.org/marketing-prohibition',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/assignee',
      'ObjectIri' = 'https://example.org/ad-network'],
     [iri_term(ex('marketing-prohibition'), 'https://example.org/marketing-prohibition'),
      iri_term(odrl(assignee), 'http://www.w3.org/ns/odrl/2/assignee'),
      rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/ad-network'), default_graph),
      iri_term(ex('ad-network'), 'https://example.org/ad-network')]).
step(rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/ad-network'), default_graph),
     fact(8),
     [],
     []).
step(rdf_link(ex('marketing-prohibition'), odrl(target), ex('lab-result')),
     rule(42),
     ['Subject' = ex('marketing-prohibition'),
      'Predicate' = odrl(target),
      'Object' = ex('lab-result'),
      'SubjectIri' = 'https://example.org/marketing-prohibition',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/target',
      'ObjectIri' = 'https://example.org/lab-result'],
     [iri_term(ex('marketing-prohibition'), 'https://example.org/marketing-prohibition'),
      iri_term(odrl(target), 'http://www.w3.org/ns/odrl/2/target'),
      rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph),
      iri_term(ex('lab-result'), 'https://example.org/lab-result')]).
step(rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph),
     fact(9),
     [],
     []).
step(rdf_link(ex('marketing-prohibition'), odrl(action), odrl(distribute)),
     rule(42),
     ['Subject' = ex('marketing-prohibition'),
      'Predicate' = odrl(action),
      'Object' = odrl(distribute),
      'SubjectIri' = 'https://example.org/marketing-prohibition',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/action',
      'ObjectIri' = 'http://www.w3.org/ns/odrl/2/distribute'],
     [iri_term(ex('marketing-prohibition'), 'https://example.org/marketing-prohibition'),
      iri_term(odrl(action), 'http://www.w3.org/ns/odrl/2/action'),
      rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph),
      iri_term(odrl(distribute), 'http://www.w3.org/ns/odrl/2/distribute')]).
step(rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph),
     fact(10),
     [],
     []).
step(rdf_link(ex('marketing-prohibition'), odrl(purpose), ex(marketing)),
     rule(42),
     ['Subject' = ex('marketing-prohibition'),
      'Predicate' = odrl(purpose),
      'Object' = ex(marketing),
      'SubjectIri' = 'https://example.org/marketing-prohibition',
      'PredicateIri' = 'http://www.w3.org/ns/odrl/2/purpose',
      'ObjectIri' = 'https://example.org/marketing'],
     [iri_term(ex('marketing-prohibition'), 'https://example.org/marketing-prohibition'),
      iri_term(odrl(purpose), 'http://www.w3.org/ns/odrl/2/purpose'),
      rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/marketing'), default_graph),
      iri_term(ex(marketing), 'https://example.org/marketing')]).
step(rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/marketing'), default_graph),
     fact(11),
     [],
     []).
step(decision_name(decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure)), deny),
     fact(53),
     [],
     []).
step(atom_concat('https://example.org/', deny, 'https://example.org/deny'), builtin, [], []).
step(result_rdf(iri('https://example.org/flow-care'), iri('https://example.org/confidence'), literal('0.92', datatype('http://www.w3.org/2001/XMLSchema#decimal')), default_graph),
     rule(48),
     ['FlowIri' = 'https://example.org/flow-care',
      'Text' = '0.92',
      'Flow' = flow_care,
      'DecisionTerm' = decision(flow_care, permit, confidence(0.92), status(executable_flow)),
      'FlowResource' = ex('flow-care'),
      'Source' = ex('hospital-a'),
      'SourceIri' = 'https://example.org/hospital-a'],
     [flow_decision(flow_care, decision(flow_care, permit, confidence(0.92), status(executable_flow))),
      decision_has_confidence(decision(flow_care, permit, confidence(0.92), status(executable_flow))),
      flow_resource(flow_care, ex('flow-care')),
      iri_term(ex('flow-care'), 'https://example.org/flow-care'),
      flow_request(flow_care, ex('hospital-a'), ex('research-partner'), ex('lab-result'), odrl(use), ex(healthcare)),
      iri_term(ex('hospital-a'), 'https://example.org/hospital-a'),
      rdf(iri('https://example.org/hospital-a'), iri('https://example.org/trustScore'), literal('0.92', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph)]).
step(decision_has_confidence(decision(flow_care, permit, confidence(0.92), status(executable_flow))),
     fact(54),
     [],
     []).
step(result_rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/confidence'), literal('0.63', datatype('http://www.w3.org/2001/XMLSchema#decimal')), default_graph),
     rule(48),
     ['FlowIri' = 'https://example.org/flow-clinic',
      'Text' = '0.63',
      'Flow' = flow_clinic,
      'DecisionTerm' = decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk)),
      'FlowResource' = ex('flow-clinic'),
      'Source' = ex('small-clinic'),
      'SourceIri' = 'https://example.org/small-clinic'],
     [flow_decision(flow_clinic, decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk))),
      decision_has_confidence(decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk))),
      flow_resource(flow_clinic, ex('flow-clinic')),
      iri_term(ex('flow-clinic'), 'https://example.org/flow-clinic'),
      flow_request(flow_clinic, ex('small-clinic'), ex('research-partner'), ex('lab-result'), odrl(use), ex(healthcare)),
      iri_term(ex('small-clinic'), 'https://example.org/small-clinic'),
      rdf(iri('https://example.org/small-clinic'), iri('https://example.org/trustScore'), literal('0.63', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph)]).
step(decision_has_confidence(decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk))),
     fact(55),
     [],
     []).
step(result_rdf(iri('https://example.org/flow-care'), iri('https://example.org/status'), iri('https://example.org/executable_flow'), default_graph),
     rule(49),
     ['FlowIri' = 'https://example.org/flow-care',
      'StatusIri' = 'https://example.org/executable_flow',
      'Flow' = flow_care,
      'DecisionTerm' = decision(flow_care, permit, confidence(0.92), status(executable_flow)),
      'Status' = executable_flow,
      'FlowResource' = ex('flow-care')],
     [flow_decision(flow_care, decision(flow_care, permit, confidence(0.92), status(executable_flow))),
      decision_status(decision(flow_care, permit, confidence(0.92), status(executable_flow)), executable_flow),
      flow_resource(flow_care, ex('flow-care')),
      iri_term(ex('flow-care'), 'https://example.org/flow-care'),
      atom_concat('https://example.org/', executable_flow, 'https://example.org/executable_flow')]).
step(decision_status(decision(flow_care, permit, confidence(0.92), status(executable_flow)), executable_flow),
     fact(56),
     ['Status' = executable_flow],
     []).
step(atom_concat('https://example.org/', executable_flow, 'https://example.org/executable_flow'),
     builtin,
     [],
     []).
step(result_rdf(iri('https://example.org/flow-ads'), iri('https://example.org/status'), iri('https://example.org/blocked_flow'), default_graph),
     rule(49),
     ['FlowIri' = 'https://example.org/flow-ads',
      'StatusIri' = 'https://example.org/blocked_flow',
      'Flow' = flow_ads,
      'DecisionTerm' = decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure)),
      'Status' = blocked_flow,
      'FlowResource' = ex('flow-ads')],
     [flow_decision(flow_ads, decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure))),
      decision_status(decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure)), blocked_flow),
      flow_resource(flow_ads, ex('flow-ads')),
      iri_term(ex('flow-ads'), 'https://example.org/flow-ads'),
      atom_concat('https://example.org/', blocked_flow, 'https://example.org/blocked_flow')]).
step(decision_status(decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure)), blocked_flow),
     fact(57),
     ['Status' = blocked_flow],
     []).
step(atom_concat('https://example.org/', blocked_flow, 'https://example.org/blocked_flow'),
     builtin,
     [],
     []).
step(result_rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/risk'), iri('https://example.org/trustworthiness_risk'), default_graph),
     rule(50),
     ['FlowIri' = 'https://example.org/flow-clinic',
      'RiskIri' = 'https://example.org/trustworthiness_risk',
      'Flow' = flow_clinic,
      'DecisionTerm' = decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk)),
      'Risk' = trustworthiness_risk,
      'FlowResource' = ex('flow-clinic')],
     [flow_decision(flow_clinic, decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk))),
      decision_risk(decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk)), trustworthiness_risk),
      flow_resource(flow_clinic, ex('flow-clinic')),
      iri_term(ex('flow-clinic'), 'https://example.org/flow-clinic'),
      atom_concat('https://example.org/', trustworthiness_risk, 'https://example.org/trustworthiness_risk')]).
step(decision_risk(decision(flow_clinic, review, confidence(0.63), risk(trustworthiness_risk)), trustworthiness_risk),
     fact(58),
     ['Risk' = trustworthiness_risk],
     []).
step(atom_concat('https://example.org/', trustworthiness_risk, 'https://example.org/trustworthiness_risk'),
     builtin,
     [],
     []).
step(result_rdf(iri('https://example.org/flow-ads'), iri('https://example.org/risk'), iri('https://example.org/unwanted_disclosure'), default_graph),
     rule(50),
     ['FlowIri' = 'https://example.org/flow-ads',
      'RiskIri' = 'https://example.org/unwanted_disclosure',
      'Flow' = flow_ads,
      'DecisionTerm' = decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure)),
      'Risk' = unwanted_disclosure,
      'FlowResource' = ex('flow-ads')],
     [flow_decision(flow_ads, decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure))),
      decision_risk(decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure)), unwanted_disclosure),
      flow_resource(flow_ads, ex('flow-ads')),
      iri_term(ex('flow-ads'), 'https://example.org/flow-ads'),
      atom_concat('https://example.org/', unwanted_disclosure, 'https://example.org/unwanted_disclosure')]).
step(decision_risk(decision(flow_ads, deny, status(blocked_flow), risk(unwanted_disclosure)), unwanted_disclosure),
     fact(59),
     ['Risk' = unwanted_disclosure],
     []).
step(atom_concat('https://example.org/', unwanted_disclosure, 'https://example.org/unwanted_disclosure'),
     builtin,
     [],
     []).
