condition('C1', resolution, ok, 116).
condition('C2', well_founded, ok, 144).
condition('C3', justification, ok, 144).
condition('C4', coverage, ok, 167).
condition('C5', re_decision, ok, 1).
condition('C6', boundary_consistency, ok, 0).
condition('C7', relevance, ok, 145).
obligation(absent, theory_scoped, \+ (member([A, red], []), member(A, [slovenia, hungary]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[croatia, red]]), member(A, [hungary, bulgaria]))).
obligation(absent, theory_scoped, \+ (member([A, green], [[romania, red], [croatia, red]]), member(A, [romania, greece]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[bulgaria, green], [romania, red], [croatia, red]]), member(A, [latvia, poland]))).
obligation(absent, theory_scoped, \+ (member([A, green], [[lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [estonia, lithuania]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [latvia]))).
obligation(absent, theory_scoped, \+ (member([A, green], [[estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [austria, italy, hungary, croatia]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [czech_republic, poland, hungary, austria]))).
obligation(absent, theory_scoped, \+ (member([A, green], [[slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [germany, poland, slovakia, austria]))).
obligation(absent, theory_scoped, \+ (member([A, blue], [[czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [austria, slovakia, romania, croatia, slovenia]))).
obligation(absent, theory_scoped, \+ (member([A, blue], [[hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [germany, czech_republic, slovakia, lithuania]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, []))).
obligation(absent, theory_scoped, \+ (member([A, red], [[malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, []))).
obligation(absent, theory_scoped, \+ (member([A, red], [[cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [sweden]))).
obligation(absent, theory_scoped, \+ (member([A, green], [[finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [finland]))).
obligation(absent, theory_scoped, \+ (member([A, yellow], [[sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [czech_republic, germany, hungary, italy, slovenia, slovakia]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [spain]))).
obligation(absent, theory_scoped, \+ (member([A, green], [[portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [france, portugal]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[spain, green], [portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [bulgaria]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[greece, red], [spain, green], [portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, []))).
obligation(absent, theory_scoped, \+ (member([A, green], [[ireland, red], [greece, red], [spain, green], [portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [germany]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[denmark, green], [ireland, red], [greece, red], [spain, green], [portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [france, austria, slovenia]))).
obligation(absent, theory_scoped, \+ (member([A, red], [[italy, red], [denmark, green], [ireland, red], [greece, red], [spain, green], [portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [netherlands, belgium, luxemburg, denmark, france, austria, poland, czech_republic]))).
obligation(absent, theory_scoped, \+ (member([A, blue], [[germany, red], [italy, red], [denmark, green], [ireland, red], [greece, red], [spain, green], [portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [spain, belgium, luxemburg, germany, italy]))).
obligation(absent, theory_scoped, \+ (member([A, green], [[france, blue], [germany, red], [italy, red], [denmark, green], [ireland, red], [greece, red], [spain, green], [portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [belgium, france, germany]))).
obligation(absent, theory_scoped, \+ (member([A, green], [[luxemburg, green], [france, blue], [germany, red], [italy, red], [denmark, green], [ireland, red], [greece, red], [spain, green], [portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [belgium, germany]))).
obligation(absent, theory_scoped, \+ (member([A, yellow], [[netherlands, green], [luxemburg, green], [france, blue], [germany, red], [italy, red], [denmark, green], [ireland, red], [greece, red], [spain, green], [portugal, red], [austria, yellow], [sweden, green], [finland, red], [cyprus, red], [malta, red], [poland, blue], [hungary, blue], [czech_republic, green], [slovakia, red], [slovenia, green], [estonia, red], [latvia, green], [lithuania, red], [bulgaria, green], [romania, red], [croatia, red]]), member(A, [france, netherlands, luxemburg, germany]))).
steps(144).
verified(116).
recomputed(0).
composed(1).
trusted(27).
claims(1).
verdict(checked_with_obligations).
